version: "3.9"

services:
  node:
    image: node:18.15.0-alpine
    ports:
      - 80:3000
    volumes:
      - type: bind
        source: ./client
        target: /app
        consistency: delegated
    tty: true
    working_dir: /app