version: "3.8"

services:
  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./api
        target: /usr/share/nginx/html/api
      - type: bind
        source: ./docker/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo

  php:
    build:
      context: .
      dockerfile: ./docker/php/dev/Dockerfile
    volumes:
      - type: bind
        source: ./api
        target: /usr/share/nginx/html/api

  mysql:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
      - type: bind
        source: ./docker/mysql/initdb.d
        target: /docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=template
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    
  mailhog:
    image: mailhog/mailhog
    ports: 
      - 8025:8025

volumes:
  mysql: